@startuml
'https://plantuml.com/sequence-diagram

class App_Controller {

FileCloseClicked()
FileOpenClicked()
FileSaveClicked()
ViewAllClicked()
ViewCompleteClicked()
ViewIncompleteClicked()
RCMarkIncompleteClicked()
RCMarkCompleteClicked()
GettingStartedClicked()
AboutClicked()

--
EditNewClicked
EditDeleteClicked
Initialize
addTodoItem
EditClearAllClicked
deleteRCClicked

}

class startScene {
main()
start()
}

App_Controller -|> startScene
App_Controller <|- startScene


@enduml