@startuml
'https://plantuml.com/sequence-diagram

class App_Controller {
Details found under
"Controller_Diagram.puml"
}

class File_Open {
run_open()
}

class File_Close {
run_close()
}

class File_Save {
run_single_save()
run_all_save()
}

class Edit {
run_new_list()
run_new_item()
}

class View {
run_view_all()
run_view_yes()
run_view_no()
}

class Item_Right_Click {
run_mark_yes()
run_mark_no()
run_rename()
run_delete()
run_redate()
}

class List_Right_Click {
run_rename()
run_delete()
}
class Help {
run_tutorial()
run_about()
}

class main_class {
main()
start()
}



App_Controller -|> main_class
App_Controller <|- main_class

Edit -- main_class
File_Close -- main_class
File_Save -- main_class
File_Open -- main_class
Item_Right_Click -- main_class
List_Right_Click -- main_class
Help -- main_class
View -- main_class



@enduml